# Generated by Django 2.1.1 on 2019-01-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='getinttouch',
            new_name='getintouch',
        ),
    ]
