# Generated by Django 2.1.1 on 2019-01-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190105_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
